language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer serve &> /dev/null &
  - cp behat.yml.dist behat.yml
  - composer install
  - composer update --prefer-dist --no-progress --no-suggest

script:
  - ./vendor/bin/behat --format=progres --no-interaction